version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ccxt
    versions:
    - 1.41.100
    - 1.41.12
    - 1.41.34
    - 1.41.41
    - 1.41.50
    - 1.41.6
    - 1.41.60
    - 1.41.62
    - 1.41.70
    - 1.41.78
    - 1.41.81
    - 1.41.89
    - 1.41.92
    - 1.41.96
    - 1.41.99
    - 1.42.18
    - 1.42.20
    - 1.42.25
    - 1.42.29
    - 1.42.39
    - 1.42.47
    - 1.42.48
    - 1.42.49
    - 1.42.52
    - 1.42.55
    - 1.42.66
    - 1.42.67
    - 1.42.71
    - 1.42.74
    - 1.42.93
    - 1.43.26
    - 1.43.37
    - 1.43.43
    - 1.43.62
    - 1.43.76
    - 1.43.89
    - 1.44.2
    - 1.44.24
    - 1.44.35
    - 1.44.4
    - 1.45.38
    - 1.45.64
    - 1.45.74
    - 1.45.84
    - 1.46.37
    - 1.46.46
    - 1.46.47
    - 1.46.71
    - 1.47.3
    - 1.47.47
    - 1.47.60
    - 1.47.66
    - 1.47.81
    - 1.48.25
    - 1.48.35
    - 1.48.41
    - 1.48.76
    - 1.48.90
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: binance-api-node
    versions:
    - 0.10.24
    - 0.10.25
    - 0.10.26
    - 0.10.28
    - 0.10.29
    - 0.10.30
    - 0.10.32
    - 0.10.33
    - 0.10.34
    - 0.10.35
    - 0.10.36
    - 0.10.37
    - 0.10.38
    - 0.10.40
  - dependency-name: "@tensorflow/tfjs-node"
    versions:
    - 2.8.6
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
    - 3.4.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
